<script>
  //Promise 실행은 바로 하되 결과값은 나중에 받는다.
  const condition = true;
  const promise = new Promise((resolve, reject) => {
    if (condition) {
      resolve('성공');
    } else {
      reject('실패');
    }
  });
  Promise.then((message) => {
    console.log(message);
  })
    .catch((error) => {
      console.log(error);
    })
    .finally(() => {
      console.log('무조건');
    });
  ///////////////////////////////////////////////////////
  Promise.then((message) => {
    return new Promise((resolve, reject) => {
      resolve(message);
    });
  })
    .then((message2) => {
      return new Promise((resolve, reject) => {
        resolve(message2);
      });
    })
    .then((message3) => {
      console.log(message3);
    })
    .catch((message4) => {
      console.log(message4);
    });
  ////////////////////////////////////////////////////
  // callback함수가 세번 중첩 되어있음 코드의 깊이가 깊어짐
  function findAndSaveUser(Users) {
    Users.findOne({}, (err, user) => {
      if (err) {
        return console.log(err);
      }
      user.name = 'zero';
      user.sava((err) => {
        if (err) {
          return console.error(err);
        }
        Users.findOne({ gender: 'm' }, (err, user) => {});
      });
    });
  }
  ////////////////////////////////////////////////////////
  // callback함수의 중첩을 해결해줌
  function findAndSaveUser(Users) {
    Users.findOne({})
      .then((user) => {
        user.name = 'zero';
        return user.save();
      })
      .then((user) => {
        return Users.findOne({ gender: 'm' });
      })
      .then((user) => {})
      .catch((err) => {
        console.error(err);
      });
  }
  ///////////////////////////////////////////////////////////
  // promise 여러 개를 동시에 사용하는 법 Promise.all
  // 중첩해서 사용 안 해도됨
  const promise1 = Promise.reslove('성공1');
  const promise2 = Promise.reslove('성공2');
  Promise.all([promise1, promise2])
    .then((result) => {
      console.log(result);
    })
    .catch((error) => {
      console.log(error);
    });
  //////////////////////////////////////////////////////////////
  // Promise.all 대신 Promise.allSettled를 사용하면
  // 정확히 어떤 프로미스에서 사용되었는지 알수 있음 -> 결과값이 자세해짐
  const promise3 = Promise.resolve('성공');
  const promise4 = Promise.reject('실패');
  const promise5 = Promise.resolve('성공2');
  Promise.allSettled([promise3, promise4, promise5])
    .then((result) => {
      console.log(result);
      // [
      //     {status: 'fulfilled',value:'성공1'},
      //     {status: 'rejected', reason:'실패2'}, //실패의 이유는 reason에 있음
      //     {status: 'fulfilled',value:'성공3'}
      // ]
    })
    .catch((error) => {
      console.error(error);
    });
  ///////////////////////////////////////////////////////////////
  // reject된 Promise에 catch를 달지 않으면 에러 발생함
  try {
    Promise.reject('에러');
  } catch (e) {
    console.error(e);
  }
  Promise.reject('에러').catch(() => {});
</script>
